### ISSUE TITLE
acbuild dos not recognize local rkt images

### ISSUE THREAD

**Issue by f0** [appc/acbuild#161] opened 2016-01-16 07:58 UTC
if you try acbuild begin example.com/app:1 and these image is only importet into the local rkt image store, acbuild does not find the image

**Comment by dgonyeo** [comment] 2016-01-19 15:19
Right now acbuild doesn't support using rkt's store. You can operate on that image by doing:

```
rkt image export example.com/app:1 app-1-linux-amd64.aci
acbuild begin app-1-linux-amd64.aci
```

There's an open issue that'll have acbuild use the same logic as rkt for its store. Once that's done you may be able to point acbuild at `/var/lib/rkt` and it'll work how you want it to, but there will need to be some way to make sure that there aren't weird version mismatches between rkt and acbuild.

**Comment by f0** [comment] 2016-01-19 16:11
@dgonyeo  i know the acbuild begin app-1-linux-amd64.aci way, thats what i use atm

**Comment by dgonyeo** [comment] 2016-02-17 21:23
Closing this, since this is kinda a duplicate of the "use rkt's cas" issue here: https://github.com/appc/acbuild/issues/125

**Closed by dgonyeo** 2016-02-17 21:23 UTC
