### ISSUE TITLE
Problem with Apache examples

### ISSUE THREAD

**Issue by dbarranco** [appc/acbuild#159] opened 2016-01-06 11:27 UTC
Everytime, when I try to build an Apache container from you examples I get the same error:
```
[root@linux ~]# apachephp.sh
Beginning build with an empty ACI
Setting name of ACI to example.com/apache-php
Adding dependency "quay.io/coreos/alpine-sh"
Running: [apk update]
Downloading quay.io/coreos/alpine-sh: [========================] 2.65 MB/2.65 MB
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
v3.2.3-149-gd036522 [http://dl-4.alpinelinux.org/alpine/v3.2/main]
OK: 5294 distinct packages available
Running: [apk add php php-apache2]
(1/16) Installing php-common (5.6.14-r0)
(2/16) Installing pcre (8.37-r1)
(3/16) Installing ncurses-terminfo-base (5.9-r3)
(4/16) Installing ncurses-libs (5.9-r3)
(5/16) Installing readline (6.3.008-r0)
(6/16) Installing libxml2 (2.9.2-r1)
(7/16) Installing php-cli (5.6.14-r0)
(8/16) Installing php (5.6.14-r0)
(9/16) Installing libuuid (2.26.2-r0)
(10/16) Installing apr (1.5.2-r0)
(11/16) Installing expat (2.1.0-r1)
(12/16) Installing apr-util (1.5.4-r0)
(13/16) Installing apache2 (2.4.16-r0)
(14/16) Installing libgcc (4.9.2-r5)
(15/16) Installing libstdc++ (4.9.2-r5)
(16/16) Installing php-apache2 (5.6.14-r0)
Executing busybox-1.23.2-r0.trigger
OK: 31 MiB in 31 packages
Running: [/bin/sh -c echo 'ServerName localhost' >> /etc/apache2/httpd.conf]
Directory /root/.acbuild/target lacks the binary to execute or doesn't look like a binary tree. Refusing.
run: exit status 1
Ending the build
```

**Comment by dgonyeo** [comment] 2016-01-08 19:49
Interesting. What version of acbuild are you running? Also does the `examples/apache/build-apache.sh` work for you?

**Comment by dghubble** [comment] 2016-02-02 23:26
I get the same issue on the `build-apache.sh` example with the latest `acbuild`.

```
acbuild version v0.2.1-28-g46ad9c4
appc version 0.7.1+git
```

```
Running: [/bin/sh -c echo 'ServerName localhost' >> /etc/apache2/httpd.conf]
Directory /home/REDACTED/.acbuild/target lacks the binary to execute or doesn't look like a binary tree. Refusing.
run: exit status 1
```

**Comment by dgonyeo** [comment] 2016-02-10 19:14
What distro are you guys running? If I can reproduce this by matching your setups, I'll be able to figure out what's causing it.

**Comment by dghubble** [comment] 2016-02-10 19:21
Fedora 23

**Comment by dbarranco** [comment] 2016-02-12 14:39
I'm on a CentOS 7

Thanks for your time

**Comment by alban** [comment] 2016-02-17 10:46
I had this on Fedora 23 as well.

**Comment by dgonyeo** [comment] 2016-02-17 20:29
I know exactly what's causing this. In the apache example `/bin/sh` is a symlink to `/bin/busybox`, and systemd-nspawn is attempting to follow the symlink before the chroot happens. If you run `touch /bin/busybox` and run `examples/apache/build-apache.sh` again it'll work.

The good news: this is the second time I've had to figure out what causes this issue, and this has already been fixed in systemd. 
https://github.com/systemd/systemd/commit/16fb773ee33a5b4e85605bf18a0572bead1b8224

The bad news: it looks like only systemd >= 228 has the fix, and Fedora 23 Workstation has systemd 222.

I'll make a PR such that `acbuild run` will check if you're exec'ing a symlink and systemd < 228, and have it print a warning.

For you fine folks, here's some workarounds. Any of these three things should make the apache example work for you.
- On line 25 in the apache example, replace `/bin/sh` with `/bin/busybox sh`
- Find a base image to use that doesn't use busybox (or have symlinks for its binaries)
- Run `touch /bin/busybox`

**Closed** 2016-02-19 18:14 UTC
Labels: area/usability, kind/bug
